version: '3'

services:

  # Postgresql
  postgres_sw:
    image: postgis/postgis:11-3.2
    env_file:
      - .env.db
    environment:
      POSTGRES_PASSWORD: spider_web

    ports:
      - 5477:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Django
  spider_web:
    image: spider_web
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres_sw
    command: "python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
