version: '3.4'

services:
  pythonsamplevscodedjangotutorial:
    image: spider_web
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python ./manage.py migrate && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 ./manage.py runserver 0.0.0.0:8000"]
    ports:
      - 8001:8000
      - 5678:5678
