version: '3'

services:

  # Postgresql
  postgres:
    image: postgres
    env_file:
      # POSTGRES_PORT não é uma variável lida pelo container
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./.docker/volumes/postgres/:/var/lib/postgresql/data

  # Django
  django:
    image: spider_web
    build:
      context: .
    ports:
      - "${DJANGO_PORT}:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    command: "python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
