# Generated by Django 4.1.6 on 2023-02-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalFileSnippetAssociatedDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.document")),
                (
                    "external_file_snippet",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.externalfilesnippet"),
                ),
            ],
        ),
    ]
