# Generated by Django 4.1.6 on 2023-03-12 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_document_name_document_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="inserted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 12, 0, 40, 42, 900451, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
    ]
