# Generated by Django 4.1.6 on 2023-03-13 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_document_inserted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("path", models.TextField()),
                ("inserted_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ExternalDocument_Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tag")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.externaldocument")),
            ],
            options={
                "unique_together": {("tag", "external_document")},
            },
        ),
    ]
