# Generated by Django 4.1.6 on 2023-03-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_externaldocument_tag_externaldocument_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="inserted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="externaldocument",
            name="inserted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
