# Generated by Django 4.1.6 on 2023-03-18 23:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_externaldocument_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldocument",
            name="description_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="externaldocument",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description_search_vector"], name="core_extern_descrip_f3ed18_gin"
            ),
        ),
    ]
