# Generated by Django 4.1.6 on 2023-03-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_externaldocument_description_search_vector_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueToUpdateDescriptionSearchVector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_id", models.IntegerField()),
            ],
        ),
    ]
