# Generated by Django 4.1.6 on 2023-03-19 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_queuetoupdatedescriptionsearchvector"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QueueToUpdateDescriptionSearchVector",
        ),
    ]
